feat: token-core support Ton chain[R2D2-13379]
consenlabs/token-core-monorepo pull request #139
Opened 2024-12-23 11:08 UTC by xiaoguang1010

## Summary of Changes
token-core support Ton chain

## Motivation and Context

## How Has This Been Tested? (Test Plan)

## Other information

## Screenshots (if appropriate):

## Final checklist

- [ ] Did you test both iOS and Android(if applicable)?
- [ ] Is a security review needed(consenlabs/security)?

## Security checklist (only for leader check)

- [ ] No backdoor risk
  - Check for unknown network request urls, and script/shell files with unclear purposes,
  - The backend service cannot expose leaked data interfaces for various reasons (even for testing purposes)
- [ ] No network communication protocol risk
  - Check whether to introduce unsafe network calls such as http/ws
- [ ] No import potentially risk 3rd library
  - Check whether 3rd dependent library is import
  - Don't use an unknown third-party library
  - Check the 3rd library sources are fetched from normal sources, such as npm, gomodule, maven, cocoapod, Do not use unknown sources
  - Check github Dependabot alerts, Whether to add new issues
- [ ] Private data not exposed
  - Check whether there are exclusive ApiKey, privatekey and other private information uploaded to git
  - Check if the packaged keystore has been uploaded to git

2024-12-24 01:57 UTC, XuNeal approved these changes

2024-12-24 01:57 UTC, XuNeal commented on token-core/tcx-constants/src/coin_info.rs
> +                derivation_path: "m/44'/607'/0'".to_string(),
这是不应该是 m/44'/607'/0'/0/0 吗？

2024-12-24 02:11 UTC, XuNeal requested changes

2024-12-24 02:11 UTC, XuNeal commented on token-core/tcx-ton/src/address.rs
> +        let non_production = match coin.network.as_str() {
一般我们叫 network 居多。这里是to_base64_url_flags 参数就是叫 no_production吗？

2024-12-24 02:11 UTC, XuNeal commented on token-core/tcx-ton/src/signer.rs
> +        let hash = Vec::from_hex_auto(&tx.hash)?;
哈希值是直接传进来的？我记得我们之前讨论是 Hash 值是需要在 tcx 实现

2024-12-24 05:43 UTC, xiaoguang1010 commented on token-core/tcx-ton/src/address.rs
> +        let non_production = match coin.network.as_str() {
是的，to_base64_url_flags的参数就叫non_production，我把这个参数名改一下吧，例如is_mainnet，这样便于理解。

2024-12-24 05:46 UTC, xiaoguang1010 commented on token-core/tcx-ton/src/signer.rs
> +        let hash = Vec::from_hex_auto(&tx.hash)?;
因为前端是直接调用的库进行序列化的，但是库开发的接口只开放了获取序列化的hash，没有开发获取获取序列化原值的接口，所以就直接传递hash结果直接进行签名了。

2024-12-24 06:05 UTC, xiaoguang1010 commented on token-core/tcx-constants/src/coin_info.rs
> +                derivation_path: "m/44'/607'/0'".to_string(),
看了trust wallet的代码，ton的address生成测试是用的slip44路径，但是都是到account级别，没有加后两层。

2024-12-24 06:19 UTC, XuNeal approved these changes

2024-12-30 08:38 UTC, XuNeal approved these changes

2025-01-02 01:15 UTC, XuNeal approved these changes

2025-01-10 09:03 UTC, XuNeal approved these changes

2025-04-03 10:22 UTC, merged