feat: open tcx scan_keystores api[R2D2-13481]
consenlabs/token-core-monorepo pull request #141
Opened 2024-12-31 03:54 UTC by xiaoguang1010

## Summary of Changes

open tcx scan_keystores api
## Motivation and Context

## How Has This Been Tested? (Test Plan)

## Other information

## Screenshots (if appropriate):

## Final checklist

- [ ] Did you test both iOS and Android(if applicable)?
- [ ] Is a security review needed(consenlabs/security)?

## Security checklist (only for leader check)

- [ ] No backdoor risk
  - Check for unknown network request urls, and script/shell files with unclear purposes,
  - The backend service cannot expose leaked data interfaces for various reasons (even for testing purposes)
- [ ] No network communication protocol risk
  - Check whether to introduce unsafe network calls such as http/ws
- [ ] No import potentially risk 3rd library
  - Check whether 3rd dependent library is import
  - Don't use an unknown third-party library
  - Check the 3rd library sources are fetched from normal sources, such as npm, gomodule, maven, cocoapod, Do not use unknown sources
  - Check github Dependabot alerts, Whether to add new issues
- [ ] Private data not exposed
  - Check whether there are exclusive ApiKey, privatekey and other private information uploaded to git
  - Check if the packaged keystore has been uploaded to git

2024-12-31 07:25 UTC, XuNeal approved these changes

2024-12-31 08:33 UTC, XuNeal approved these changes

2025-01-03 01:16 UTC, XuNeal approved these changes

2025-01-08 07:55 UTC, xwartz commented on token-core/tcx/src/handler.rs
> +            let is_migrated = is_migrated_keystore(&keystore.id());
新创建的 wallet，is_migrated 字段会是什么值？

2025-01-08 08:00 UTC, xwartz commented on token-core/tcx/src/handler.rs
> +            let is_migrated = is_migrated_keystore(&keystore.id());
应该要区分出来
- 215 新创建的
- 215 迁移过的
- 215 未迁移的

2025-01-08 08:13 UTC, xiaoguang1010 commented on token-core/tcx/src/handler.rs
> +            let is_migrated = is_migrated_keystore(&keystore.id());
> 新创建的 wallet，is_migrated 字段会是什么值？

新创建的wallet应该会是false，这个只有_migrated.json里面存在的钱包id，才位ture。

2025-01-08 08:30 UTC, xiaoguang1010 commented on token-core/tcx/src/handler.rs
> +            let is_migrated = is_migrated_keystore(&keystore.id());
> 应该要区分出来
> 
> * 215 新创建的
> * 215 迁移过的
> * 215 未迁移的
> 
> 已经迁移过的 keystore，前端可以不管，未迁移的前端恢复 wallet 时，要标记未迁移状态，后续会进行迁移。
> 
> 所以，前端得区分出上面三种类型的 keystore

我的理解：
1. “scan_keystores”接口返回的is_migrated标识，if ture -->迁移过的，if false-->新建的
2. 如果要确定哪些是未迁移的，那么就需要调用“scan_legacy_keystores”，如果返回的keystore不包含在“scan_keystores”接口返回的列表中，则表示这个keystore是未迁移的。
@XuNeal 不知道我理解是否有问题。

2025-01-08 08:35 UTC, xwartz commented on token-core/tcx/src/handler.rs
> +            let is_migrated = is_migrated_keystore(&keystore.id());
那和我理解不太一样了，我以为 scan_keystores 接口返回的是所有的 keystore，包括 215 之前的(迁移和未迁移的)和 215 之后创建的

2025-01-08 09:20 UTC, xiaoguang1010 commented on token-core/tcx/src/handler.rs
> +            let is_migrated = is_migrated_keystore(&keystore.id());
旧的keystone可以通过“scan_legacy_keystores”来获取到。

2025-01-09 05:54 UTC, XuNeal requested changes

2025-01-09 05:54 UTC, XuNeal commented on token-core/tcx/src/migration.rs
> +        (WALLET_V2_DIR, false) => "new".to_string(),
@xiaoguang1010 需要确认这里如果两个老的 keystore 都有相同的助记词，并且都迁移之后，这里是否会正确的返回migrated

2025-01-09 05:54 UTC, XuNeal commented on token-core/tcx/src/api.rs
> +    pub status: ::prost::alloc::string::String,
这里直接叫 status 太过于generic 了。建议改成 migration_status

2025-01-09 06:27 UTC, xiaoguang1010 commented on token-core/tcx/src/migration.rs
> +        (WALLET_V2_DIR, false) => "new".to_string(),
会返回migrated，两个相同的助记词keystore，迁移后都在_migrated.json里标注，这个标识的判断依据是id是否在_migrated.json中。

2025-01-10 00:50 UTC, closed without merging