feat: add BLSToExecutionEhange signature feature
consenlabs/token-core-monorepo pull request #23
Opened 2023-03-30 00:46 UTC by xiaoguang1010

https://imtoken.atlassian.net/jira/software/projects/LABS/boards/12?selectedIssue=LABS-1429

2023-03-30 03:02 UTC, XuNeal requested changes

2023-03-30 03:02 UTC, XuNeal commented on token-core/tcx-primitive/Cargo.toml
> +bls-signatures = { git = "https://github.com/XuNeal/bls-signatures.git", branch = "feat/pop_dst" }
blst 库支持 自定义 cipher suite  https://github.com/supranational/blst
示例代码参见
```rust
use blst::{min_pk, min_sig, PublicKey, SecretKey};

fn main() {
    // 生成密钥对
    let sk = SecretKey::key_gen(&[42; 32]).unwrap();
    let pk = PublicKey::from(&sk);

    // 签名
    let msg = b"Hello, BLS!";
    let dst = b"BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_";
    let sig = min_sig::sign(msg, &sk, dst).unwrap();

    // 验证签名
    let result = min_pk::verify(&sig, msg, &pk, dst);
    assert!(result.is_ok());
}
```
可以尝试把这个fork的 bls-signatures 替换一下

2023-03-30 03:14 UTC, xiaoguang1010 commented
build

2023-03-30 06:32 UTC, merged

2023-04-03 06:28 UTC, xiaoguang1010 commented on token-core/tcx-eth2/src/bls_to_execution_change.rs
> +        //todo
这个本来是想加一个长度校验呢，后来看了一下没必要，所以删掉就行。

2023-04-03 06:32 UTC, xiaoguang1010 commented on token-core/tcx-primitive/Cargo.toml
> +bls-signatures = { git = "https://github.com/XuNeal/bls-signatures.git", branch = "feat/pop_dst" }
已使用blst库替换。
另外blst sign函数传入参数的正确顺序为：
let sig = min_sig::sign(msg, dst, aug).unwrap();

2023-04-03 06:37 UTC, xiaoguang1010 commented on token-core/tcx-eth2/src/lib.rs
> +pub fn hex_to_bytes(value: &str) -> Result<Vec<u8>> {
token-core中目前没有一个公共使用的工具库，后续根据需要再加上吧。