feat: add generate_mnemonic and create_identity  api[7670,7671]
consenlabs/token-core-monorepo pull request #40
Opened 2023-05-29 10:21 UTC by xiaoguang1010

add generate_mnemonic and create_identity  api

2023-05-30 02:45 UTC, XuNeal requested changes

2023-05-31 07:01 UTC, xiaoguang1010 commented on token-core/tcx-wallet/src/identity.rs
> +fn create_identity(
这个函数忽略掉，忘记删了。

2023-05-31 07:02 UTC, xiaoguang1010 commented on token-core/tcx-wallet/src/identity.rs
> +    use crate::identity::{create_identity, IdentityKeystore};
等把ETH导入功能开发完后，会参照android-token-core中的用例补全。

2023-06-13 09:38 UTC, XuNeal commented on token-core/tcx/src/handler.rs
> +    let param: ExportIdentityParam = ExportIdentityParam::decode(data)?;
这边免密后面再考虑是吧。

2023-06-26 07:34 UTC, xiaoguang1010 commented on token-core/tcx-eth/src/address.rs
> +        todo!()
验证代码已补齐

2023-06-26 07:51 UTC, xiaoguang1010 commented on token-core/tcx-wallet/src/imt_keystore.rs
> +            version: VERSION,
是的，后续实现create_hd可以再单独定义一个，目前ETH没有用到create_hd，所以还没有实现。

2023-06-26 08:16 UTC, xiaoguang1010 commented on token-core/tcx/src/handler.rs
> +    let current_identity: GetCurrentIdentityResult =
CreateIdentityResult是定义的接口struct，用于接口数据传递。IdentityKeystore是一个keystore文件对象，直接拿IdentityKeystore进行接口数据的传递感觉不太合适。

2023-06-26 08:38 UTC, xiaoguang1010 commented on token-core/tcx/src/handler.rs
> +    identity_keystore: &IdentityKeystore,
1. 确实传入metadata就可以，传入IdentityKeystore现在参数太大了。
2. 不是静态函数，函数里面吧数据保存到lazy_static里面了。

2023-06-26 08:39 UTC, xiaoguang1010 commented on token-core/tcx/src/handler.rs
> +    let param: ExportIdentityParam = ExportIdentityParam::decode(data)?;
是的

2023-06-26 09:07 UTC, xiaoguang1010 commented
build android

2023-06-26 09:12 UTC, XuNeal approved these changes

2023-06-30 01:40 UTC, XuNeal requested changes

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx-eth/src/signer.rs
> +        let mut ret_access_list = AccessList::default();
这边
let access_items = self.access_list.iter().map(|item| {AccessLisItem{}).collect();
Ok(AccessList::from(access_items)) 会不会更好一些。不用声明一个mut并且不用直接调用ret_access_list.0 这种未命名的字段

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx-eth/src/types.rs
> +impl Default for Action {
这个 Action 很多地方导入了，但是是干什么用的呢？

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx-proto/src/wallet_api.proto
> +    string ipfs_id = 2;
大小写

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx-proto/src/wallet_api.proto
> +    string mnemonic_path = 4;
大小写记得统一

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx-wallet/src/identity.rs
> +        Mnemonic::validate(mnemonic_phrase, Language::English).unwrap();
这边直接 unwrap() 前端应该没法正常处理吧？

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx-wallet/src/identity.rs
> +        let mnemonic = Mnemonic::from_phrase(mnemonic_phrase, Language::English).unwrap();
phrase 不会 正常validate吗？

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx-wallet/src/identity.rs
> +        WalletManager::create_wallet(imt_keystore.to_owned())?;
create_wallet 代表的什么意思？给dentity添加关联？flushing文件？

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx-wallet/src/identity.rs
> +        let mut keystore_context = String::new();
这里是想拼content?

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx-wallet/src/imt_keystore.rs
> +        _ => return Err(Error::WalletInvalidType.into()),
这是什么意思？这段代码应该是错误的吧？

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx-wallet/src/wallet_manager.rs
> +        //TODO
rust 可以使用 unimplemented 宏

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx-wallet/src/wallet_manager.rs
> +            _ => Err(Error::WalletInvalidType.into()),
感觉抛WalletInvalidType 好像不太合适

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx/Cargo.toml
> +ethereum-types = "0.14.0"
咦，使用了ethers-rs 了还需要用 ethereum-types吗？

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx/src/handler.rs
> +    *WALLET_KEYSTORE_DIR.write() = file_dir.to_string();
这个和上面那个区别是什么？这个是特指identity的keystore还是旧的keystore？

2023-06-30 01:40 UTC, XuNeal commented on token-core/tcx/src/handler.rs
> +pub(crate) fn sign_transaction(data: &[u8]) -> Result<Vec<u8>> {
咦，这个sign_message不能和之前已经在 tcx的连里面共用吗？
你看下面的handler中有 sign_tx 了

2023-06-30 01:55 UTC, XuNeal requested changes

2023-06-30 01:55 UTC, XuNeal commented on token-core/tcx-common/src/utility.rs
> +use keccak_hash::keccak;
一般叫做util就可以了

2023-06-30 01:55 UTC, XuNeal commented on token-core/tcx-common/src/utility.rs
> +pub fn get_address_from_pubkey(public_key: &[u8]) -> Result<String> {
这个是eth专用的获取地址的地方吧，为啥放在这里？

2023-06-30 01:55 UTC, XuNeal commented on token-core/tcx-eth/src/address.rs
> +pub fn is_valid_address(address: &str) -> Result<bool> {
咦。这边直接用bool不就行了？所有失败的直接返回false 还是说需要告诉对方无效的原因？告诉对方无效原因应该是 validate(xxx) -> Result(()) 更合适一些

2023-06-30 01:55 UTC, XuNeal commented on token-core/tcx-proto/src/eth.proto
> +  optional bool is_hex = 3;
注意大小写

2023-06-30 01:55 UTC, XuNeal commented on token-core/tcx/src/handler.rs
> +            return Err(format_err!("{}", "key_type_error"));
这边应该可以直接format_err!("key_type_error")  ?

2023-06-30 01:55 UTC, XuNeal commented on token-core/tcx/src/handler.rs
> +pub(crate) fn eth_sign_personal(data: &[u8]) -> Result<Vec<u8>> {
personalSign 和 signMessage 应该是有很多重叠的地方，可以合并到一起。

2023-06-30 01:55 UTC, XuNeal commented on token-core/tcx/src/lib.rs
> +        "eth_sign_personal" => landingpad(|| eth_sign_personal(&action.param.unwrap().value)),
这两个API在前端应该是一个API。

2023-06-30 06:10 UTC, XuNeal commented
这个PR的名字为啥会这么奇怪？叫做 feat: add identity and eth chain 会不会更准确一些？

2023-06-30 14:26 UTC, fengweiqiang-coder approved these changes

2023-07-03 02:18 UTC, XuNeal approved these changes

2023-07-11 04:13 UTC, xiaoguang1010 commented on token-core/tcx-crypto/src/crypto.rs
>      fn set_salt(&mut self, salt: &str);
也可以直接赋值，这里用到trait，把设置的方式通过方法来设置，一来跟原先的salt的设置方式保持统一，二来通过T::default()的方式获取声明struct的时候不用标注具体类型了。

2023-07-11 04:21 UTC, xiaoguang1010 commented on token-core/tcx-crypto/src/crypto.rs
> +        let mac = Self::generate_mac(&derived_key, &ciphertext);
尝试修改了一下，但是调用generate_mac有多个地方，而且有些地方只获取了self的不可变引用，无法调用这个可变应用的方法。

2023-07-11 04:37 UTC, xiaoguang1010 commented on token-core/tcx/src/handler.rs
> +    *WALLET_KEYSTORE_DIR.write() = file_dir.to_string();
这个是identity的keystore，原先以为这两个地址可能会不一样，所以想把identity的keystore和原先token-core-x生成的keystore区分开来。但是后来确认这两个地址是一样的，后续可以把两个进行合并。

2023-07-11 04:40 UTC, xiaoguang1010 commented on token-core/tcx/src/handler.rs
> +pub(crate) fn sign_transaction(data: &[u8]) -> Result<Vec<u8>> {
不可以，因为keystore接口不一样的原因，所以获取密钥的方式会不一样，以后keystore接口统一后才可以共用。

2023-07-11 07:20 UTC, xiaoguang1010 commented on token-core/tcx/src/lib.rs
> +        "eth_sign_personal" => landingpad(|| eth_sign_personal(&action.param.unwrap().value)),
我看token-v2 android 原生的代码是分着的呀，personal签名的接口调用的personalSign，message签名调用的是sign。
https://github.com/consenlabs/token-v2/blob/poc/token-core-poc/TokenTurboModules/android/src/main/java/org/consenlabs/imtoken/nativemodule/walletapi/WalletModuleImpl.java

2023-07-12 02:56 UTC, XuNeal requested changes

2023-07-12 02:56 UTC, XuNeal commented on token-core/tcx-eth/src/address.rs
>      let ethAddrRegex = Regex::new(r"^(0x)?[0-9a-fA-F]{40}$").unwrap();
注意变量命名统一

2023-07-12 02:56 UTC, XuNeal commented on token-core/tcx-eth/src/address.rs
>      let address_temp = &address[2..];
这边不用起新的名字，后面不用address之后直接用variable shadowing 功能就可以了。 let address = &address[2..]

2023-07-12 02:56 UTC, XuNeal commented on token-core/tcx-eth/src/address.rs
> +            u8::from_str_radix(&hash_str.chars().nth(i).unwrap().to_string(), 16).unwrap();
感觉这里 nth 返回的就是 Some(&str) 哎，还需要 & to_string() 吗？

2023-07-12 02:56 UTC, XuNeal commented on token-core/tcx-eth/src/signer.rs
> +        let signature = format!("{}{}", "0x", sign_result.to_string());
咦，感觉这个 format! 说了很多遍了，字符串常量直接在第一个参数就行嘞 format!("0x{}")....

2023-07-12 02:56 UTC, XuNeal commented on token-core/tcx/src/handler.rs
> +            created_at: imt_keystore.metadata.clone().unwrap().timestamp,
这边是不是直接clone一个 metadata 然后后面的直接用这个 metadata 就可以了？timestamp 应该是默认实现了 Copy 其他的大部分to_string() 应该用可以，虽然也有复制，但不是metadata 复制了三份。

2023-07-12 02:56 UTC, XuNeal commented on token-core/tcx/src/handler.rs
> +pub(crate) fn sign_transaction(data: &[u8]) -> Result<Vec<u8>> {
能名字似乎更明确一些比较合适，比如叫 legacy_sign_tx 。叫 sign_transaction 和 sign_tx 名字很容易混淆。不知道为啥存在两个看起来功能一样，但是名字不一样的函数。

2023-07-12 02:56 UTC, XuNeal commented on token-core/tcx/src/lib.rs
> +        "eth_sign_personal" => landingpad(|| eth_sign_personal(&action.param.unwrap().value)),
不不不， 其实这里面名字很乱，常说的 personalSign 在web3js叫做 web3.eth.personal.sign 在 ethersjs 中叫做 signMessage. 在 go 的 ETH 节点中叫做 eth_sign. 
但大部分情况下一般人还是认为 signMessgae 和 personalSign 是同一个接口，用来签名带 \x19Ethereum Signed Message:\n<length of message> 的内容。 而 ecSign 或者 sign 测试用来签名不带 header 的内容。

2023-07-12 03:05 UTC, xiaoguang1010 commented on token-core/tcx-eth/src/address.rs
> +            u8::from_str_radix(&hash_str.chars().nth(i).unwrap().to_string(), 16).unwrap();
返回的是&char。

2023-07-12 03:19 UTC, XuNeal commented
ETH Address没有单元测试吗？

2023-07-12 03:20 UTC, XuNeal commented
感觉handler.rs 中很多 create_identity 中的代码可以从handler.rs 移除，切换到 identity 本身所在的 tcx-wallet 中

2023-07-12 03:21 UTC, XuNeal commented
![Uploading 图片.png…]()
这个是还打算继续优化吗？

2023-07-12 03:30 UTC, XuNeal commented
<img width="1406" alt="图片" src="https://github.com/consenlabs/token-core-monorepo/assets/10441775/58fe79d4-e71d-4b88-b4b9-92cecd6a67c1">

2023-07-12 03:56 UTC, XuNeal commented
<img width="1243" alt="图片" src="https://github.com/consenlabs/token-core-monorepo/assets/10441775/0ce486d2-802a-40ef-82a1-0305733e457d">
<img width="914" alt="图片" src="https://github.com/consenlabs/token-core-monorepo/assets/10441775/77f30d1c-763f-40d5-a24a-aa45c68c8a0c">
这边是不是有 bug，看起来重复添加了 eth 钱包的 id 。

2023-07-12 06:14 UTC, XuNeal commented
<img width="1203" alt="图片" src="https://github.com/consenlabs/token-core-monorepo/assets/10441775/befbc2c1-80ec-4b67-beb3-76d905931d48">
<img width="1523" alt="图片" src="https://github.com/consenlabs/token-core-monorepo/assets/10441775/e3566898-3a60-4e0d-af85-fe6f80d2f1c2">
目前这个结构看起来有些混乱啊，本身 IdentityKeystore 已经实现了 derive_etheum_wallet 方法，但是却在 handler.rs 中又实现了一个 derive_ethereum_wallet 函数，其中还使用了几个 WalletManager*, Identity的静态函数。

在之前的 android-token-core 中抽象结构是 Keystore -> Wallet -> WalletManager 。Keystore 负责数据的序列化和反序列化， Wallet 负责钱包的功能封装。 WalletManager 是作为和 RN 通讯的一个界面。目前在 Rust 中已经有 call_tcx_api 作为界面了就不需要 WalletManager 了。

静态函数无法利用对象数据状态，无法实现多态，扩展性比较差。除了很多完全无副作用，简短的功能例如 hex::encode。大部分情况下静态函数在不是首选设计。

2023-07-12 06:27 UTC, XuNeal commented
另外目前我看到有240个warning了。可以按照warning修一修。

2023-07-13 08:31 UTC, XuNeal approved these changes

2023-07-13 08:32 UTC, xiaoguang1010 commented
> 感觉handler.rs 中很多 create_identity 中的代码可以从handler.rs 移除，切换到 identity 本身所在的 tcx-wallet 中

2023-07-14 07:00 UTC, XuNeal approved these changes

2023-07-31 03:15 UTC, XuNeal commented on token-core/tcx-common/Cargo.toml
> +rust-crypto = "0.2.36"
rust-crypto 不要用了，这个上次更新是7年前了。要用 https://github.com/rustcrypto 项目开发的其他库。

2023-07-31 03:15 UTC, XuNeal commented on token-core/tcx-common/Cargo.toml
> +rust-crypto = "0.2.36"
keccak-hash , hmac-sha256 等其他库也直接改成 rustcrypto 项目组开发的。 RustCrypto 项目组目前还必要活跃，统一的话后面不用担心不维护或者风格不统一之类的。

2023-12-06 09:26 UTC, closed without merging