feat: imKey support subaddress feature[R2D2-10114]
consenlabs/token-core-monorepo pull request #58
Opened 2024-01-10 01:37 UTC by xiaoguang1010

- imkey support subaddress feat
- add imkey subaddress test case

2024-01-10 02:11 UTC, XuNeal commented on imkey-core/ikc-wallet/coin-cosmos/src/address.rs
> +            parent_fingerprint: Fingerprint::default(),
这里 Fingerprint 及下面的 fingerprint 都会变成空吧。看起来返回的xpub 应该会受影响啊。

2024-01-10 02:11 UTC, XuNeal commented on imkey-core/ikc-wallet/coin-eos/src/pubkey.rs
> +    pub fn get_xpub(path: &str) -> Result<String> {
这个 get_xpub 能重用吗？看起来 EOS 和 cosmos 都拷贝了一份

2024-01-10 02:11 UTC, XuNeal commented on imkey-core/ikc-wallet/coin-filecoin/src/address.rs
> +        let uncomprs_pubkey: String = res_msg_pubkey.chars().take(194).collect();
改动这个单元测试是因为？

2024-01-10 02:19 UTC, xiaoguang1010 commented on imkey-core/ikc-wallet/coin-filecoin/src/address.rs
> +        let uncomprs_pubkey: String = res_msg_pubkey.chars().take(194).collect();
为了复用这个函数，把返回扩展公钥的chaincode加上，可以单纯获取公钥用，也可以生成xpub使用。

2024-01-10 02:46 UTC, xiaoguang1010 commented on imkey-core/ikc-wallet/coin-cosmos/src/address.rs
> +            parent_fingerprint: Fingerprint::default(),
父公钥是默认值，但是子公钥中的fingerprint是通过父公钥的公钥生成的，并做了设置，所以对返回的xpub应该是没有影响的。
let fingerprint_obj = parent_ext_pub_key.fingerprint();
let extend_public_key = ExtendedPubKey {
            network: Network::Bitcoin,
            depth: chain_number_vec.len() as u8,
            parent_fingerprint: fingerprint_obj,
            child_number: *chain_number_vec.get(chain_number_vec.len() - 1).unwrap(),
            public_key: pub_key_obj,
            chain_code: sub_chain_code_obj,
        };

2024-01-10 07:48 UTC, xiaoguang1010 commented on imkey-core/ikc-wallet/coin-eos/src/pubkey.rs
> +    pub fn get_xpub(path: &str) -> Result<String> {
整个生成的逻辑基本一样，但是不同的币种选取的应用不一样，地址这块实现目前实现比较零散，上午想把地址这块整体结构整理一下，改了一半发现改动太大，后续专门找时间把这块专门优化一下吧。

2024-01-11 06:30 UTC, tyrone98 requested changes

2024-01-11 06:30 UTC, tyrone98 commented on imkey-core/ikc/src/handler.rs
> +                account_rsp.public_key = format!("0x{}", public_key);
我们的 public_key 返回应当全是小写吧，这里好像变成大写

2024-01-12 07:26 UTC, xiaoguang1010 commented on imkey-core/ikc-common/src/path.rs
> +    if !(2..=10).contains(&depth) || path.len() > 100 {
这种写法是cargo clippy推荐的，所以就改了这种写法。
<2 or >10 这种写法确认看起来比较清晰，可以把他改回来。

2024-01-12 07:59 UTC, xiaoguang1010 commented on imkey-core/ikc-wallet/coin-cosmos/src/address.rs
> -        let uncomprs_pubkey: String = res_msg_pubkey
这里返回公钥为了能复用，所以返回非压缩的，生成地址的时候会转换为压缩的格式，这样会有问题吗？

2024-01-12 10:41 UTC, xiaoguang1010 commented on imkey-core/ikc-common/src/path.rs
> +    let re = Regex::new(r"^m/[0-9'/]+$").unwrap();
把这个正则校验去掉吧，看了一下其他库关于path的校验，都没有校验的这么完整，一般是可以通过“/”split，以及以m开头就可以了，而且这个path可能会有各种不同的定义。

2024-01-12 10:42 UTC, xiaoguang1010 commented on imkey-core/ikc/src/handler.rs
> +                account_rsp.public_key = format!("0x{}", public_key);
已统一返回小些处理。

2024-01-15 01:58 UTC, tyrone98 commented on imkey-core/ikc-wallet/coin-cosmos/src/address.rs
> -        let uncomprs_pubkey: String = res_msg_pubkey
我指的应当是 uncompress, uncomprs 没有这种简称啊

2024-01-16 13:47 UTC, merged